variables:
  # Set to true to skip tests
  SKIP_TESTS: "false"

stages:
  - test
  - trigger

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:
  except:
    variables:
      - $SKIP_TESTS == "true"
  stage: test
  image: ubuntu:focal
  services:
    - docker:dind
  tags:
    - mender-qa-worker-generic
  variables:
    # DinD setup in Mender CI runners
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS_VERIFY: "1"
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - apt-get update && apt-get install -y
      docker.io bash git openssl pwgen python3 jq docker-compose wget sudo
    - git config --global user.name "user"
    - git config --global user.email "user@example.com"
  script:
    - ./run-tests.sh

test:internal-links:
  stage: test
  image: node:19-alpine
  script:
    - apk add --no-cache git
    - npm ci
    - ./checklinks.js --color --verbose


test:latest_versions:
  stage: test
  image: alpine
  before_script:
    - apk add --no-cache git python3 py3-pip
    - pip3 install pyyaml
    - export INTEGRATION_REPO_DIR=/tmp/integration
    - git clone https://github.com/mendersoftware/integration.git $INTEGRATION_REPO_DIR
    - export INTEGRATION_VERSION=origin/staging
  script:
    - ./autoversion.py
      --update
      --integration-dir $INTEGRATION_REPO_DIR
      --integration-version $INTEGRATION_VERSION
      --mender-ci-workflows-version 1.0.0
    - git diff HEAD
    # exits with non zero status if not staged for commit files exist
    - git diff-index --quiet HEAD
  only:
    - /^(hosted)$/

.trigger:mender-docs-site:
  stage: trigger
  inherit:
    variables: false
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|hosted|[0-9]+\.[0-9]+\.x)$/'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never

trigger:mender-docs-site:master:
  extends: .trigger:mender-docs-site
  trigger:
    project: Northern.tech/Mender/mender-docs-site
    branch: master

trigger:mender-docs-site:production:
  extends: .trigger:mender-docs-site
  trigger:
    project: Northern.tech/Mender/mender-docs-site
    branch: production
